Layout/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false
  CountRepeatedAttributes: true

Metrics/MethodLength:
  Max: 40

Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/NumericLiterals:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - '.irbrc'
    - 'lib/specimen/cli/*.rb'
    - 'lib/specimen/commands.rb'
    - 'lib/specimen/extensions/**/*/*.rb'
